name: Website Deployment
on:
  push:
    branches:
      - main
defaults:
  run:
    working-directory: starting-project-01-04
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Test code
        id: run-tests # set the id to whatever you want
        continue-on-error: true # we can gibe this an expression as well instead of hardcoding "true"
        run: npm run test
      - name: Upload test report
        # for "if", we can omit the use of ${{}} as for this key, the value is typically and expression
        # this as is will still not execute, we need 1 more function
        # if: steps.run-tests.outcome == 'failure'
        # if: failure() && steps.run-tests.outcome == 'failure'
        # here we can use another method: "continue-on-error"
        # this is set on the step before this so that the execution contines even if the step fails
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: ./starting-project-01-04/test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build website
        id: build-website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: ./starting-project-01-04/dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    # Override the workflow default just for this job:
    defaults:
      run:
        working-directory: . # or: ${{ github.workspace }}
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: Output contents
        run: ls
      - name: Deploy
        run: echo "Deploying..."
  report:
    needs: [lint, deploy]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: output information
        working-directory: .
        run: |
          echo something when wrong
          echo "${{ toJSON(github) }}"
  use-reusable-deploy:
    needs: build
    uses: ./.github/workflows/reusable.yml
    with:
      artifact-name: dist-files
  print-deploy-result:
    needs: use-reusable-deploy
    runs-on: ubuntu-latest
    steps:
      - name: print reusable workflow output
        working-directory: .
        run: echo ${{ needs.use-reusable-deploy.outputs.result }}
