name: matrix demo
on: push
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [12, 14]
        operating-system: [ubuntu-latest, windows-latest]
        # other values can be used here, we can name the keys whatever we want
        exclude:
          - node-version: 12
            operating-system: windows-latest
        include:
          - node-version: 18
            operating-system: ubuntu-latest
    runs-on: ${{ matrix.operating-system }}
    defaults:
      run:
        working-directory: starting-project-01-04
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: install deps
        run: npm ci
      - name: build
        run: npm run build
