name: Practice 04 - as Jobs
on: push

defaults:
  run:
    working-directory: 04-Practice-Project-(Start)

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repo
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm lint
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repo
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm test
  BuildAndDeploy:
    runs-on: ubuntu-latest
    needs: [Lint, Test]
    steps:
      - name: Get code from repo
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm build
      - name: Deploy
        run: echo "Deploying..."
