name: Test project
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repo
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          cd Starting-Project-02
          npm install
      - name: Run tests
        run: |
          cd Starting-Project-02
          npm test
